pubpath: ../public
svn_url: http://tarski.googlecode.com/svn
git_repo: git://github.com/ionfish/tarski.git

feed:
  url: http://tarskitheme.com/
  title: Tarski update notification
  author: [Benedict Eastaugh, Chris Sternal-Johnson]
